# Generated by Django 5.2.4 on 2025-08-22 07:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100)),
                ('dob', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='user_photo/')),
                ('profile_video', models.FileField(blank=True, null=True, upload_to='user_video/')),
                ('bio', models.TextField()),
                ('role', models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('Team Leader', 'Team Leader')], max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.state')),
            ],
        ),
    ]
