# Generated by Django 5.2.4 on 2025-08-26 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usermanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='profile_video',
            field=models.FileField(blank=True, null=True, upload_to='user_video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])]),
        ),
    ]
